In [1]:
import pandas as pd

import numpy as np

In [3]:
df = pd.read_csv(r'C:/Users/Friend/OneDrive/Desktop/Ecommerce/Population_Analysis/population_by_country_2020.csv', encoding='latin-1')

In [4]:
df

,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,China,1440297825,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,India,1382345085,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,United States,331341050,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,Indonesia,274021604,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,Pakistan,221612785,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...
230,Montserrat,4993,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
231,Falkland Islands,3497,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
232,Niue,1628,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
233,Tokelau,1360,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
234,Holy See,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [5]:
df.head(10)

,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,China,1440297825,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,India,1382345085,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,United States,331341050,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,Indonesia,274021604,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,Pakistan,221612785,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
5,Brazil,212821986,0.72 %,1509890,25,8358140,21200.0,1.7,33,88 %,2.73 %
6,Nigeria,206984347,2.58 %,5175990,226,910770,-60000.0,5.4,18,52 %,2.64 %
7,Bangladesh,164972348,1.01 %,1643222,1265,130170,-369501.0,2.1,28,39 %,2.11 %
8,Russia,145945524,0.04 %,62206,9,16376870,182456.0,1.8,40,74 %,1.87 %
9,Mexico,129166028,1.06 %,1357224,66,1943950,-60000.0,2.1,29,84 %,1.65 %

In [6]:
df.tail(15)

,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
220,Caribbean Netherlands,26265,0.94 %,244,80,328,NaN,N.A.,N.A.,75 %,0.00 %
221,Palau,18109,0.48 %,86,39,460,NaN,N.A.,N.A.,N.A.,0.00 %
222,Cook Islands,17567,0.09 %,16,73,240,NaN,N.A.,N.A.,75 %,0.00 %
223,Anguilla,15026,0.90 %,134,167,90,NaN,N.A.,N.A.,N.A.,0.00 %
224,Tuvalu,11817,1.25 %,146,393,30,NaN,N.A.,N.A.,62 %,0.00 %
225,Wallis & Futuna,11203,-1.69 %,-193,80,140,NaN,N.A.,N.A.,0 %,0.00 %
226,Nauru,10836,0.63 %,68,541,20,NaN,N.A.,N.A.,N.A.,0.00 %
227,Saint Barthelemy,9882,0.30 %,30,470,21,NaN,N.A.,N.A.,0 %,0.00 %
228,Saint Helena,6080,0.30 %,18,16,390,NaN,N.A.,N.A.,27 %,0.00 %
229,Saint Pierre & Miquelon,5789,-0.48 %,-28,25,230,NaN,N.A.,N.A.,100 %,0.00 %
230,Montserrat,4993,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
231,Falkland Islands,3497,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
232,Niue,1628,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
233,Tokelau,1360,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
234,Holy See,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Country (or dependency)  235 non-null    str
 1   Population (2020)        235 non-null    int64
 2   Yearly Change            235 non-null    str
 3   Net Change               235 non-null    int64
 4   Density (P/KmÂ²)         235 non-null    int64
 5   Land Area (KmÂ²)         235 non-null    int64
 6   Migrants (net)           201 non-null    float64
 7   Fert. Rate               235 non-null    str
 8   Med. Age                 235 non-null    str
 9   Urban Pop %              235 non-null    str
 10  World Share              235 non-null    str
dtypes: float64(1), int64(4), str(6)
memory usage: 27.4 KB

In [8]:
df.describe()

,Population (2020),Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net)
count,2.350000e+02,2.350000e+02,235.000000,2.350000e+02,201.000000
mean,3.322744e+07,3.460878e+05,475.770213,5.535918e+05,6.283582
std,1.353034e+08,1.128260e+06,2331.285935,1.687796e+06,123291.887548
min,8.010000e+02,-3.838400e+05,0.000000,0.000000e+00,-653249.000000
25%,3.994905e+05,4.240000e+02,37.000000,2.545000e+03,-10047.000000
50%,5.460109e+06,3.917000e+04,95.000000,7.724000e+04,-852.000000
75%,2.067170e+07,2.496600e+05,239.500000,4.038200e+05,9741.000000
max,1.440298e+09,1.358663e+07,26337.000000,1.637687e+07,954806.000000

In [9]:
df.shape

(235, 11)

In [10]:
df = df.fillna(0)

In [11]:
df.isnull().sum()

Country (or dependency)    0
Population (2020)          0
Yearly Change              0
Net Change                 0
Density (P/KmÂ²)           0
Land Area (KmÂ²)           0
Migrants (net)             0
Fert. Rate                 0
Med. Age                   0
Urban Pop %                0
World Share                0
dtype: int64

In [12]:
df.shape

(235, 11)

In [13]:
df.head()

,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,China,1440297825,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,India,1382345085,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,United States,331341050,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,Indonesia,274021604,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,Pakistan,221612785,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %

In [14]:
maxpop = df["Population (2020)"].max()
print("The maximum population is:", maxpop)

The maximum population is: 1440297825

In [15]:
minpop = df["Population (2020)"].min()
print("The minimum population is:", minpop)

The minimum population is: 801